export const de = {
  translation: {
    PASSWORD_MUST_HAVE: "Das Passwort muss folgende Bedingungen erfüllen: ",
    PASS_CHARS: "min. acht Zeichen lang",
    LOWER_CASE: "min. einen Kleinbuchstaben",
    UPPER_CASE: "min. einen Großbuchstaben",
    DIGIT: "min. eine Zahl",
    SPECIAL_CHAR: "min. ein Sonderzeichen",
    SUBMIT: "Absenden",
    TERMS_OF_SERVICE: "AGB",
    VIEW_OUR: "Sehen Sie unsere ",
    EMAIL: "Email",
    PASSWORD: "Passwort",
    CONFIRM_PASSWORD: "Passwort bestätigen",
    OK: "OK",
    CANCEL: "Cancel",
    WRONG_PASSWORD: "Falsches Passwort",
    TRY_AGAIN: "Versuche es bitte noch einmal.",
    ERROR: "Fehler",
    TOO_MANY_REQUESTS: "Zu viele Versuche",
    TRY_AGAIN_LATER: "Bitte versuche es später wieder.",
    SOMETHING_WRONG: "Etwas ist schief gelaufen.",
    NAME: "Name",
    LOGIN: "Einloggen",
    SIGNUP: "Registrieren",
    AUTH: "Authentifizierung",
    MAPS: "Karten",
    CLICK_ON_MAP: "Klicke auf die Karte um Wegpunkte zu setzen.",
    WAYPOINTS: "Wegpunkte",
    POS: "Pos.",
    DISTANCE: "Strecke",
    HOME: "Home",
    MAP_VIEW: "Karten",
    WELCOME: "Willkommen auf hager-web.com",
    APP_DEV: "Appentwicklung",
    WE_DEV_APPS: "Wir entwickeln Apps fürs Web und Mobil",
    ABOUT_ME:
      "Mein Name ist Sven Hager, seit Oktober 2019 freiberuflich, selbständiger, Web-/Appentwickler. Als autodidakt und learnaholic halte ich mich stets auf dem neuesten Stand und entwickle, soweit möglich und erwünscht immer nach dem aktuellen Stand der Technik. Mit meinen umfangreichen Kenntnissen und Erfahrungen im Javascript/Typescript basierten Front- und Backendbereich unterstütze ich Sie gern mit bis zu 20 Wochenstunden.",
    SKILLS:
      "Zu meinen Schwerpunkten gehört der sogenannte MERN-Stack, also MongoDB, ExpressJS, ReactJS und NodeJS. Außerdem für native iOS- und Android-Apps: React-Native. Die gängigen Tools wie Redux(Toolkit), React-Router, Axios, i18n, google-maps-api, ..., gehören selbstverständlich ebenfalls zu meinen täglichen Begleitern.",
    MORE_SKILLS:
      "Zusätzlich verfüge ich über erste Erfahrungen im Unit-Testing mit React-Testing-Library und Jest und erweitere gerade meine Erfahrungen zu Test-Driven-Development (TDD).",
    DRAWER_MENU:
      "Über das Drawermenü können Sie auf weitere Seiten navigieren, wo sie einige Beispiele zu meinen bereits (mehrfach) umgesetzen Features finden.",
    REPOSITORY:
      "Um sich ein Bild von meinem Code machen zu können, finden Sie den gesamten Quellcode dieser Seite unter folgendem Link:",
    LINKS: "Links",
    IMPRINT: "Impressum",
    PRIVACY: "Datenschutz",
    SOCIAL_MEDIA: "Social media",
    REFERENCES: "Referenzen",
    MOBILE_APPS: "iOS/Android Apps",
    LOGOUT: "Abmelden",
    HELLO: "Hallo",
    SUCCESS: "Erfolgreich",
    LOGGED_OUT: "Sie sind ausgeloggt.",
    OH_NO: "Oh nein",
    ATTENTION: "Achtung",
    LOGGED_IN: "Login erfolgreich",
    SIGNED_UP: "Registrierung erfolgreich",
    REACT_APPLICATION: "React Anwendung",
    COOKIE_HEADING:
      "Diese Seite verwendet sogenannte Cookies um die Benutzerfreundlichkeit zu erhöhen",
    COOKIE_SECOND:
      "Wenn Sie damit nicht einverstanden sind, kann das Ihre Benutzererfahrung einschränken",
    AGREE: "Einverstanden",
    DENY: "Ablehnen",
    KEEP_LOGGED_IN: "Eingeloggt bleiben",
  },
};
