export const en = {
  translation: {
    PASSWORD_MUST_HAVE: "Password must fulfill the following conditions: ",
    PASS_CHARS: "min. eight characters long",
    LOWER_CASE: "min. one lower case letter",
    UPPER_CASE: "min. one upper case letter",
    DIGIT: "min. one digit",
    SPECIAL_CHAR: "min. one special char",
    SUBMIT: "Submit",
    TERMS_OF_SERVICE: "terms of service",
    VIEW_OUR: "View our ",
    EMAIL: "Email",
    PASSWORD: "Password",
    CONFIRM_PASSWORD: "Confirm-password",
    OK: "OK",
    CANCEL: "Cancel",
    WRONG_PASSWORD: "Wrong password",
    TRY_AGAIN: "Please try again.",
    ERROR: "Error",
    TOO_MANY_REQUESTS: "Too many requests",
    TRY_AGAIN_LATER: "Please try again later.",
    SOMETHING_WRONG: "Something went wrong.",
    NAME: "Name",
    LOGIN: "Login",
    SIGNUP: "Signup",
    AUTH: "Authentication",
    MAPS: "Maps",
    CLICK_ON_MAP: "Click on map to set waypoints.",
    WAYPOINTS: "Waypoints",
    POS: "Pos.",
    DISTANCE: "Distance",
    HOME: "Home",
    MAP_VIEW: "Maps",
    WELCOME: "Welcome to hager-web.com",
    APP_DEV: "Appdevelopement",
    WE_DEV_APPS: "We develop apps for web and mobile",
    ABOUT_ME:
      "My name is Sven Hager, freelance, self-employed, web/app developer since October 2019. As an autodidact and learnaholic, I always keep myself up to date and, as far as possible and desired, always develop according to the current state of the art. With my extensive knowledge and experience in the Javascript/Typescript based front- and backend area, I am happy to support you with up to 20 hours per week.",
    SKILLS:
      "My focus is on the so-called MERN stack, i.e. MongoDB, ExpressJS, ReactJS and NodeJS. Also, for native iOS and Android apps: React-Native. The common tools such as Redux(Toolkit), React-Router, Axios, i18n, google-maps-api, ..., are of course also part of my daily companions.",
    MORE_SKILLS:
      "Additionally, I have first experiences in unit testing with React-Testing-Library and Jest and am currently expanding my experiences in Test-Driven-Development (TDD).",
    DRAWER_MENU:
      "Via the drawer menu you can navigate to further pages, where you will find some examples of my already (repeatedly) implemented features.",
    REPOSITORY:
      "To get an idea of my code, you can find the entire source code of this page under the following link:",

    LINKS: "Links",
    IMPRINT: "Imprint",
    PRIVACY: "Privacy",
    SOCIAL_MEDIA: "Social media",
    REFERENCES: "References",
    MOBILE_APPS: "iOS/Android Apps",
    LOGOUT: "Logout",
    HELLO: "Hello",
    SUCCESS: "Success",
    LOGGED_OUT: "You are logged out.",
    OH_NO: "Oh no",
    ATTENTION: "Attention",
    LOGGED_IN: "Login successful",
    SIGNED_UP: "Signup successful",
    REACT_APPLICATION: "React application",
    COOKIE_HEADING:
      "This site uses so-called cookies to increase the user-experience",
    COOKIE_SECOND:
      "If you do not agree to this, it may limit your user experience",
    AGREE: "Agree",
    DENY: "Deny",
    KEEP_LOGGED_IN: "Keep me loged in",
    TITLE: "Title",
    ADD_LIST: "Add a list",
    ADD_ITEM: "Add item",
    CONTENT: "Content",
    DRAG_N_DROP: "Drag N Drop",
  },
};
