export const de = {
  translation: {
    PASSWORD_MUST_HAVE: "Das Passwort muss folgende Bedingungen erfüllen: ",
    PASS_CHARS: "min. acht Zeichen lang",
    LOWER_CASE: "min. einen Kleinbuchstaben",
    UPPER_CASE: "min. einen Großbuchstaben",
    DIGIT: "min. eine Zahl",
    SPECIAL_CHAR: "min. ein Sonderzeichen",
    SUBMIT: "Absenden",
    TERMS_OF_SERVICE: "AGB",
    VIEW_OUR: "Sehen Sie unsere ",
    EMAIL: "Email",
    PASSWORD: "Passwort",
    CONFIRM_PASSWORD: "Passwort bestätigen",
    OK: "OK",
    CANCEL: "Cancel",
    WRONG_PASSWORD: "Falsches Passwort",
    TRY_AGAIN: "Versuche es bitte noch einmal.",
    ERROR: "Fehler",
    TOO_MANY_REQUESTS: "Zu viele Versuche",
    TRY_AGAIN_LATER: "Bitte versuche es später wieder.",
    SOMETHING_WRONG: "Etwas ist schief gelaufen.",
    NAME: "Name",
    LOGIN: "Einloggen",
    SIGNUP: "Registrieren",
    AUTH: "Authentifizierung",
    MAPS: "Karten",
    CLICK_ON_MAP: "Klicke auf die Karte um Wegpunkte zu setzen.",
    WAYPOINTS: "Wegpunkte",
    POS: "Pos.",
    DISTANCE: "Strecke",
  },
};
