export const en = {
  translation: {
    PASSWORD_MUST_HAVE: "Password must fulfill the following conditions: ",
    PASS_CHARS: "min. eight characters long",
    LOWER_CASE: "min. one lower case letter",
    UPPER_CASE: "min. one upper case letter",
    DIGIT: "min. one digit",
    SPECIAL_CHAR: "min. one special char",
    SUBMIT: "Submit",
    TERMS_OF_SERVICE: "terms of service",
    VIEW_OUR: "View our ",
    EMAIL: "email",
    PASSWORD: "password",
    CONFIRM_PASSWORD: "confirm-password",
    OK: "OK",
    CANCEL: "Cancel",
    WRONG_PASSWORD: "Wrong password",
    TRY_AGAIN: "Please try again.",
    ERROR: "Error",
    TOO_MANY_REQUESTS: "Too many requests",
    TRY_AGAIN_LATER: "Please try again later.",
    SOMETHING_WRONG: "Something went wrong.",
    NAME: "Name",
  },
};
